[package]
name = "autosharing_heuristics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
tokio = { version = "1.26.0", features = ["rt", "time", "macros", "rt-multi-thread"] }
