[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/autosharing"]

[project]
name="autosharing_heuristics"
version="0.1"
dependencies = [
  "numpy",
]
